module.exports=[
    {
        "key":"Spain",
        "value":141
    },
    {
        "key":"Taiwan Province of China",
        "value":112
    },
    {
        "key":"China",
        "value":92
    },
    {
        "key":"Singapore",
        "value":81
    },
    {
        "key":"Malaysia",
        "value":76
    },
    {
        "key":"France",
        "value":76
    },
    {
        "key":"Korea, Republic of",
        "value":70
    },
    {
        "key":"Italy",
        "value":70
    },
    {
        "key":"Indonesia",
        "value":59
    },
    {
        "key":"Mexico",
        "value":58
    }
];
