module.exports = [
  {
    "key": "Strains",
    "value": 579,
    "taxonomy": [
      "Freshwater fishes",
      "Molluscs",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes",
      "Miscellaneous aquatic animal products"
    ],
    "country": [
      "China",
      "India",
      "Viet Nam",
      "Norway",
      "Indonesia",
      "Egypt",
      "Bangladesh",
      "Myanmar",
      "Chile",
      "Ecuador",
      "Korea, Republic of",
      "Brazil",
      "Thailand",
      "Philippines",
      "Spain",
      "United Kingdom",
      "Japan",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "United States of America",
      "Mexico",
      "Turkey",
      "New Zealand",
      "Faroe Islands",
      "Canada",
      "Russian Federation",
      "Italy",
      "Korea, Dem. People's Rep",
      "Cambodia",
      "Lao People's Dem. Rep.",
      "France",
      "Peru",
      "Ghana",
      "Netherlands",
      "Australia",
      "Taiwan Province of China",
      "Colombia",
      "Pakistan",
      "Saudi Arabia",
      "Uganda",
      "Malaysia",
      "Honduras",
      "Iraq",
      "Uzbekistan",
      "Nicaragua",
      "Venezuela, Boliv Rep of",
      "Zambia",
      "Greece",
      "Czechia",
      "Ireland",
      "Poland",
      "Germany",
      "Tunisia",
      "Guatemala",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Nepal",
      "Denmark",
      "Hungary",
      "Armenia",
      "Zimbabwe",
      "Kenya",
      "Ukraine",
      "Tanzania, United Rep. of",
      "Belarus",
      "Panama",
      "Israel",
      "Afghanistan",
      "El Salvador",
      "Paraguay",
      "Croatia",
      "Madagascar",
      "Malawi",
      "Sudan",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Sweden",
      "Portugal",
      "Finland",
      "Bolivia (Plurinat.State)",
      "Burundi",
      "Lesotho",
      "Haiti",
      "Brunei Darussalam",
      "French Polynesia",
      "Belize",
      "Syrian Arab Republic",
      "Lebanon",
      "Algeria",
      "Kyrgyzstan",
      "Jordan",
      "Dominican Republic",
      "Kazakhstan",
      "C�te d'Ivoire",
      "R�union",
      "US Virgin Islands",
      "Iceland",
      "Latvia",
      "Slovenia",
      "Singapore"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "Southern Asia",
      "South-Eastern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Southern Europe",
      "Western Africa",
      "Northern America",
      "Central America",
      "Western Asia",
      "Australia and New Zealand",
      "Eastern Europe",
      "Western Europe",
      "Eastern Africa",
      "Central Asia",
      "Caribbean",
      "Middle Africa",
      "Southern Africa",
      "Polynesia"
    ]
  },
  {
    "key": "Varieties",
    "value": 42,
    "taxonomy": "Aquatic plants",
    "country": [
      "China",
      "Indonesia",
      "Philippines",
      "Korea, Republic of",
      "Korea, Dem. People's Rep",
      "Japan",
      "Malaysia",
      "Zanzibar",
      "Madagascar",
      "Chile",
      "Solomon Islands",
      "Viet Nam",
      "Tanzania, United Rep. of",
      "Papua New Guinea",
      "Kiribati",
      "Cambodia",
      "India",
      "Timor-Leste",
      "Fiji",
      "Kenya",
      "Bulgaria"
    ],
    "continent": [
      "Asia",
      "Africa",
      "Americas",
      "Oceania",
      "Europe"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Eastern Africa",
      "South America",
      "Melanesia",
      "Micronesia",
      "Southern Asia",
      "Eastern Europe"
    ]
  },
  {
    "key": "Varieties",
    "value": 42,
    "taxonomy": "Aquatic plants",
    "country": [
      "China",
      "Indonesia",
      "Philippines",
      "Korea, Republic of",
      "Korea, Dem. People's Rep",
      "Japan",
      "Malaysia",
      "Zanzibar",
      "Madagascar",
      "Chile",
      "Solomon Islands",
      "Viet Nam",
      "Tanzania, United Rep. of",
      "Papua New Guinea",
      "Kiribati",
      "Cambodia",
      "India",
      "Timor-Leste",
      "Fiji",
      "Kenya",
      "Bulgaria"
    ],
    "continent": [
      "Asia",
      "Africa",
      "Americas",
      "Oceania",
      "Europe"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Eastern Africa",
      "South America",
      "Melanesia",
      "Micronesia",
      "Southern Asia",
      "Eastern Europe"
    ]
  },
  {
    "key": "Captive propagated",
    "value": 621,
    "taxonomy": [
      "Aquatic plants",
      "Freshwater fishes",
      "Molluscs",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes",
      "Miscellaneous aquatic animal products"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Myanmar",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Brazil",
      "Thailand",
      "Spain",
      "Malaysia",
      "United Kingdom",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "United States of America",
      "Mexico",
      "Zanzibar",
      "Turkey",
      "New Zealand",
      "Faroe Islands",
      "Canada",
      "Russian Federation",
      "Italy",
      "Cambodia",
      "Lao People's Dem. Rep.",
      "France",
      "Peru",
      "Ghana",
      "Netherlands",
      "Australia",
      "Taiwan Province of China",
      "Colombia",
      "Pakistan",
      "Saudi Arabia",
      "Uganda",
      "Honduras",
      "Iraq",
      "Uzbekistan",
      "Nicaragua",
      "Venezuela, Boliv Rep of",
      "Zambia",
      "Greece",
      "Czechia",
      "Ireland",
      "Poland",
      "Madagascar",
      "Germany",
      "Tunisia",
      "Guatemala",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Nepal",
      "Denmark",
      "Hungary",
      "Armenia",
      "Solomon Islands",
      "Zimbabwe",
      "Kenya",
      "Ukraine",
      "Tanzania, United Rep. of",
      "Belarus",
      "Panama",
      "Israel",
      "Afghanistan",
      "El Salvador",
      "Paraguay",
      "Croatia",
      "Malawi",
      "Sudan",
      "Papua New Guinea",
      "Kiribati",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Sweden",
      "Portugal",
      "Finland",
      "Bolivia (Plurinat.State)",
      "Timor-Leste",
      "Burundi",
      "Lesotho",
      "Haiti",
      "Brunei Darussalam",
      "French Polynesia",
      "Belize",
      "Syrian Arab Republic",
      "Lebanon",
      "Algeria",
      "Kyrgyzstan",
      "Jordan",
      "Dominican Republic",
      "Kazakhstan",
      "Fiji",
      "C�te d'Ivoire",
      "R�union",
      "Bulgaria",
      "US Virgin Islands",
      "Iceland",
      "Latvia",
      "Slovenia",
      "Singapore"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Southern Europe",
      "Western Africa",
      "Northern America",
      "Central America",
      "Eastern Africa",
      "Western Asia",
      "Australia and New Zealand",
      "Eastern Europe",
      "Western Europe",
      "Central Asia",
      "Caribbean",
      "Melanesia",
      "Micronesia",
      "Middle Africa",
      "Southern Africa",
      "Polynesia"
    ]
  }
];
