module.exports = [
  {
    "key": "Strains",
    "value": 579,
    "specie": [
      "Ctenopharyngodon idellus",
      "Crassostrea spp",
      "Ruditapes philippinarum",
      "Hypophthalmichthys molitrix",
      "Hypophthalmichthys nobilis",
      "Cyprinus carpio",
      "Carassius spp",
      "Catla catla",
      "Pectinidae",
      "Pangasius spp",
      "Salmo salar",
      "Chanos chanos",
      "Oreochromis niloticus",
      "Procambarus clarkii",
      "Penaeus vannamei",
      "Labeo rohita",
      "Mytilidae",
      "Sinonovacula constricta",
      "Clarias spp",
      "Osteichthyes",
      "Megalobrama amblycephala",
      "Eriocheir sinensis",
      "Mollusca",
      "Mylopharyngodon piceus",
      "Pangasianodon hypophthalmus",
      "Channa argus",
      "Pelteobagrus fulvidraco",
      "Micropterus salmoides",
      "Cyprinidae",
      "Oreochromis aureus x O. niloticus",
      "Misgurnus anguillicaudatus",
      "Silurus asotus",
      "Monopterus albus",
      "Anadara granosa",
      "Mytilus chilensis",
      "Siniperca chuatsi",
      "Oreochromis (=Tilapia) spp",
      "Trionyx sinensis",
      "Crassostrea gigas",
      "Penaeus monodon",
      "Rapana spp",
      "Macrobrachium nipponense",
      "Ictalurus punctatus",
      "Apostichopus japonicus",
      "Anguilla japonica",
      "Cirrhinus mrigala",
      "Mugilidae",
      "Larimichthys croceus",
      "Oncorhynchus mykiss",
      "Oncorhynchus kisutch",
      "Lateolabrax japonicus",
      "Clarias gariepinus",
      "Scylla paramamosain",
      "Haliotis spp",
      "Osphronemus goramy",
      "Seriola quinqueradiata",
      "Macrobrachium rosenbergii",
      "Patinopecten yessoensis",
      "Epinephelus spp",
      "Trachinotus blochii",
      "Portunus spp",
      "Crassostrea virginica",
      "Colossoma macropomum",
      "Clarias gariepinus x C. macrocephalus",
      "Dicentrarchus labrax",
      "Perna canaliculus",
      "Penaeus spp",
      "Cipangopaludina chinensis",
      "Siluroidei",
      "Rana spp",
      "Perna viridis",
      "Acipenseridae",
      "Rhopilema spp",
      "Piaractus brachypomus",
      "Sparidae",
      "Mytilus coruscus",
      "Metapenaeus spp",
      "Anodonta cygnea",
      "Sciaenops ocellatus",
      "Palaemonidae",
      "Scylla serrata",
      "Mytilus galloprovincialis",
      "Pagrus auratus",
      "Bivalvia",
      "Sparus aurata",
      "Bothidae",
      "Mytilus edulis",
      "Penaeus japonicus",
      "Testudinata",
      "Psetta maxima",
      "Invertebrata",
      "Rachycentron canadum",
      "Channa striata",
      "Anabas testudineus",
      "Barbonymus gonionotus",
      "Paralichthys olivaceus",
      "Oreochromis mossambicus",
      "Penaeus chinensis",
      "P. mesopotamicus x C. macropomum",
      "Channa micropeltes",
      "Osteochilus hasselti",
      "Labeo calbasu",
      "Seriola spp",
      "Argyrosomus regius",
      "Takifugu rubripes",
      "Mercenaria mercenaria",
      "Crassostrea iredalei",
      "Sebastes schlegeli",
      "Corbicula fluminea",
      "Leiocassis longirostris",
      "Protosalanx hyalocranius",
      "Pangasius pangasius",
      "Penaeus merguiensis",
      "Ascidiacea",
      "Salmonidae",
      "Perna perna",
      "Atrina spp",
      "Lates niloticus",
      "Thunnus orientalis",
      "Scylla olivacea",
      "Brachyura",
      "Pleuronectidae",
      "Piaractus mesopotamicus",
      "Trichogaster pectoralis",
      "Hypomesus olidus",
      "Argopecten purpuratus",
      "Salmo spp",
      "Eleutheronema tetradactylum",
      "Channa spp",
      "Strongylocentrotus spp",
      "Heteropneustes fossilis",
      "Clarias batrachus",
      "Thunnus maccoyii",
      "Papyrocranus afer",
      "Lutjanus argentimaculatus",
      "Lates calcarifer",
      "Pagrus major",
      "Gymnarchus niloticus",
      "C. macropomum x P. brachypomus",
      "Lutjanus johnii",
      "Takifugu obscurus",
      "Helostoma temminckii",
      "Puntius spp",
      "Cirrhinus microlepis",
      "Heterotis niloticus",
      "Hemibagrus nemurus",
      "Systomus sarana",
      "Oreochromis shiranus",
      "Ostreidae",
      "Plecoglossus altivelis",
      "Brycon spp",
      "Probarbus jullieni",
      "Leptobarbus hoeveni",
      "Arapaima gigas",
      "Oreochromis andersonii",
      "Crassostrea madrasensis",
      "Osteobrama belangeri",
      "Cirrhinus molitorella",
      "Leporinus spp",
      "Brycon amazonicus",
      "Prochilodus spp",
      "Ruditapes decussatus",
      "Tilapia rendalli",
      "Prochilodus reticulatus",
      "Anguilla anguilla",
      "Rutilus rutilus",
      "Crassostrea corteziensis",
      "Oncorhynchus tshawytscha",
      "Oreochromis aureus",
      "Penaeus stylirostris",
      "Pinctada margaritifera",
      "Thunnus thynnus",
      "Oreochromis macrochir",
      "Salmo trutta",
      "Prochilodus nigricans",
      "Tinca tinca",
      "Hoplias spp",
      "Oxyeleotris marmorata",
      "Carassius carassius",
      "Lutjanus guttatus",
      "Astyanax fasciatus",
      "Salmonoidei",
      "Abramis brama",
      "Rana catesbeiana",
      "Holothuroidea",
      "Panulirus spp",
      "Silurus glanis",
      "Holothuria scabra",
      "Cerastoderma edule",
      "Ostrea edulis",
      "Salvelinus alpinus",
      "Astacidae, Cambaridae",
      "Mugil cephalus",
      "Cromileptes altivelis",
      "Meretrix lusoria"
    ],
    "taxonomy": [
      "Freshwater fishes",
      "Molluscs",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes",
      "Miscellaneous aquatic animal products"
    ],
    "country": [
      "China",
      "India",
      "Viet Nam",
      "Norway",
      "Indonesia",
      "Egypt",
      "Bangladesh",
      "Myanmar",
      "Chile",
      "Ecuador",
      "Korea, Republic of",
      "Brazil",
      "Thailand",
      "Philippines",
      "Spain",
      "United Kingdom",
      "Japan",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "United States of America",
      "Mexico",
      "Turkey",
      "New Zealand",
      "Faroe Islands",
      "Canada",
      "Russian Federation",
      "Italy",
      "Korea, Dem. People's Rep",
      "Cambodia",
      "Lao People's Dem. Rep.",
      "France",
      "Peru",
      "Ghana",
      "Netherlands",
      "Australia",
      "Taiwan Province of China",
      "Colombia",
      "Pakistan",
      "Saudi Arabia",
      "Uganda",
      "Malaysia",
      "Honduras",
      "Iraq",
      "Uzbekistan",
      "Nicaragua",
      "Venezuela, Boliv Rep of",
      "Zambia",
      "Greece",
      "Czechia",
      "Ireland",
      "Poland",
      "Germany",
      "Tunisia",
      "Guatemala",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Nepal",
      "Denmark",
      "Hungary",
      "Armenia",
      "Zimbabwe",
      "Kenya",
      "Ukraine",
      "Tanzania, United Rep. of",
      "Belarus",
      "Panama",
      "Israel",
      "Afghanistan",
      "El Salvador",
      "Paraguay",
      "Croatia",
      "Madagascar",
      "Malawi",
      "Sudan",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Sweden",
      "Portugal",
      "Finland",
      "Bolivia (Plurinat.State)",
      "Burundi",
      "Lesotho",
      "Haiti",
      "Brunei Darussalam",
      "French Polynesia",
      "Belize",
      "Syrian Arab Republic",
      "Lebanon",
      "Algeria",
      "Kyrgyzstan",
      "Jordan",
      "Dominican Republic",
      "Kazakhstan",
      "C�te d'Ivoire",
      "R�union",
      "US Virgin Islands",
      "Iceland",
      "Latvia",
      "Slovenia",
      "Singapore"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "Southern Asia",
      "South-Eastern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Southern Europe",
      "Western Africa",
      "Northern America",
      "Central America",
      "Western Asia",
      "Australia and New Zealand",
      "Eastern Europe",
      "Western Europe",
      "Eastern Africa",
      "Central Asia",
      "Caribbean",
      "Middle Africa",
      "Southern Africa",
      "Polynesia"
    ]
  },
  {
    "key": "Varieties",
    "value": 42,
    "specie": [
      "Laminaria japonica",
      "Eucheuma spp",
      "Gracilaria spp",
      "Porphyra spp",
      "Undaria pinnatifida",
      "Kappaphycus alvarezii",
      "Algae",
      "Porphyra tenera",
      "Sargassum fusiforme",
      "Eucheuma denticulatum",
      "Spirulina spp",
      "Capsosiphon fulvescens",
      "Monostroma nitidum",
      "Codium fragile",
      "Enteromorpha clathrata",
      "Haematococcus pluvialis",
      "Chlorella vulgaris"
    ],
    "taxonomy": "Aquatic plants",
    "country": [
      "China",
      "Indonesia",
      "Philippines",
      "Korea, Republic of",
      "Korea, Dem. People's Rep",
      "Japan",
      "Malaysia",
      "Zanzibar",
      "Madagascar",
      "Chile",
      "Solomon Islands",
      "Viet Nam",
      "Tanzania, United Rep. of",
      "Papua New Guinea",
      "Kiribati",
      "Cambodia",
      "India",
      "Timor-Leste",
      "Fiji",
      "Kenya",
      "Bulgaria"
    ],
    "continent": [
      "Asia",
      "Africa",
      "Americas",
      "Oceania",
      "Europe"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Eastern Africa",
      "South America",
      "Melanesia",
      "Micronesia",
      "Southern Asia",
      "Eastern Europe"
    ]
  },
  {
    "key": "Wild sourced",
    "value": 621,
    "specie": [
      "Laminaria japonica",
      "Eucheuma spp",
      "Ctenopharyngodon idellus",
      "Crassostrea spp",
      "Ruditapes philippinarum",
      "Hypophthalmichthys molitrix",
      "Hypophthalmichthys nobilis",
      "Gracilaria spp",
      "Cyprinus carpio",
      "Carassius spp",
      "Catla catla",
      "Pectinidae",
      "Porphyra spp",
      "Undaria pinnatifida",
      "Kappaphycus alvarezii",
      "Pangasius spp",
      "Salmo salar",
      "Chanos chanos",
      "Oreochromis niloticus",
      "Procambarus clarkii",
      "Penaeus vannamei",
      "Labeo rohita",
      "Mytilidae",
      "Sinonovacula constricta",
      "Clarias spp",
      "Osteichthyes",
      "Megalobrama amblycephala",
      "Eriocheir sinensis",
      "Mollusca",
      "Mylopharyngodon piceus",
      "Algae",
      "Porphyra tenera",
      "Pangasianodon hypophthalmus",
      "Channa argus",
      "Pelteobagrus fulvidraco",
      "Micropterus salmoides",
      "Cyprinidae",
      "Oreochromis aureus x O. niloticus",
      "Misgurnus anguillicaudatus",
      "Silurus asotus",
      "Monopterus albus",
      "Anadara granosa",
      "Mytilus chilensis",
      "Siniperca chuatsi",
      "Oreochromis (=Tilapia) spp",
      "Trionyx sinensis",
      "Crassostrea gigas",
      "Penaeus monodon",
      "Rapana spp",
      "Macrobrachium nipponense",
      "Ictalurus punctatus",
      "Apostichopus japonicus",
      "Anguilla japonica",
      "Cirrhinus mrigala",
      "Sargassum fusiforme",
      "Mugilidae",
      "Larimichthys croceus",
      "Oncorhynchus mykiss",
      "Oncorhynchus kisutch",
      "Lateolabrax japonicus",
      "Clarias gariepinus",
      "Scylla paramamosain",
      "Haliotis spp",
      "Osphronemus goramy",
      "Seriola quinqueradiata",
      "Macrobrachium rosenbergii",
      "Patinopecten yessoensis",
      "Epinephelus spp",
      "Trachinotus blochii",
      "Portunus spp",
      "Crassostrea virginica",
      "Eucheuma denticulatum",
      "Colossoma macropomum",
      "Clarias gariepinus x C. macrocephalus",
      "Dicentrarchus labrax",
      "Perna canaliculus",
      "Penaeus spp",
      "Cipangopaludina chinensis",
      "Siluroidei",
      "Rana spp",
      "Perna viridis",
      "Acipenseridae",
      "Rhopilema spp",
      "Piaractus brachypomus",
      "Sparidae",
      "Mytilus coruscus",
      "Spirulina spp",
      "Metapenaeus spp",
      "Anodonta cygnea",
      "Sciaenops ocellatus",
      "Palaemonidae",
      "Scylla serrata",
      "Mytilus galloprovincialis",
      "Pagrus auratus",
      "Bivalvia",
      "Sparus aurata",
      "Bothidae",
      "Mytilus edulis",
      "Penaeus japonicus",
      "Testudinata",
      "Psetta maxima",
      "Invertebrata",
      "Rachycentron canadum",
      "Channa striata",
      "Anabas testudineus",
      "Barbonymus gonionotus",
      "Paralichthys olivaceus",
      "Oreochromis mossambicus",
      "Penaeus chinensis",
      "P. mesopotamicus x C. macropomum",
      "Channa micropeltes",
      "Osteochilus hasselti",
      "Labeo calbasu",
      "Seriola spp",
      "Argyrosomus regius",
      "Takifugu rubripes",
      "Mercenaria mercenaria",
      "Crassostrea iredalei",
      "Sebastes schlegeli",
      "Corbicula fluminea",
      "Leiocassis longirostris",
      "Protosalanx hyalocranius",
      "Pangasius pangasius",
      "Penaeus merguiensis",
      "Ascidiacea",
      "Salmonidae",
      "Perna perna",
      "Atrina spp",
      "Lates niloticus",
      "Thunnus orientalis",
      "Scylla olivacea",
      "Brachyura",
      "Pleuronectidae",
      "Piaractus mesopotamicus",
      "Trichogaster pectoralis",
      "Hypomesus olidus",
      "Argopecten purpuratus",
      "Salmo spp",
      "Eleutheronema tetradactylum",
      "Channa spp",
      "Strongylocentrotus spp",
      "Heteropneustes fossilis",
      "Clarias batrachus",
      "Thunnus maccoyii",
      "Papyrocranus afer",
      "Lutjanus argentimaculatus",
      "Lates calcarifer",
      "Pagrus major",
      "Gymnarchus niloticus",
      "C. macropomum x P. brachypomus",
      "Lutjanus johnii",
      "Takifugu obscurus",
      "Capsosiphon fulvescens",
      "Monostroma nitidum",
      "Helostoma temminckii",
      "Puntius spp",
      "Cirrhinus microlepis",
      "Heterotis niloticus",
      "Hemibagrus nemurus",
      "Systomus sarana",
      "Oreochromis shiranus",
      "Ostreidae",
      "Plecoglossus altivelis",
      "Brycon spp",
      "Probarbus jullieni",
      "Leptobarbus hoeveni",
      "Arapaima gigas",
      "Oreochromis andersonii",
      "Crassostrea madrasensis",
      "Osteobrama belangeri",
      "Cirrhinus molitorella",
      "Codium fragile",
      "Leporinus spp",
      "Enteromorpha clathrata",
      "Brycon amazonicus",
      "Prochilodus spp",
      "Ruditapes decussatus",
      "Tilapia rendalli",
      "Prochilodus reticulatus",
      "Anguilla anguilla",
      "Rutilus rutilus",
      "Crassostrea corteziensis",
      "Oncorhynchus tshawytscha",
      "Oreochromis aureus",
      "Penaeus stylirostris",
      "Pinctada margaritifera",
      "Thunnus thynnus",
      "Oreochromis macrochir",
      "Salmo trutta",
      "Prochilodus nigricans",
      "Tinca tinca",
      "Hoplias spp",
      "Oxyeleotris marmorata",
      "Carassius carassius",
      "Lutjanus guttatus",
      "Astyanax fasciatus",
      "Salmonoidei",
      "Abramis brama",
      "Rana catesbeiana",
      "Holothuroidea",
      "Panulirus spp",
      "Silurus glanis",
      "Haematococcus pluvialis",
      "Holothuria scabra",
      "Cerastoderma edule",
      "Ostrea edulis",
      "Chlorella vulgaris",
      "Salvelinus alpinus",
      "Astacidae, Cambaridae",
      "Mugil cephalus",
      "Cromileptes altivelis",
      "Meretrix lusoria"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Freshwater fishes",
      "Molluscs",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes",
      "Miscellaneous aquatic animal products"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Myanmar",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Brazil",
      "Thailand",
      "Spain",
      "Malaysia",
      "United Kingdom",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "United States of America",
      "Mexico",
      "Zanzibar",
      "Turkey",
      "New Zealand",
      "Faroe Islands",
      "Canada",
      "Russian Federation",
      "Italy",
      "Cambodia",
      "Lao People's Dem. Rep.",
      "France",
      "Peru",
      "Ghana",
      "Netherlands",
      "Australia",
      "Taiwan Province of China",
      "Colombia",
      "Pakistan",
      "Saudi Arabia",
      "Uganda",
      "Honduras",
      "Iraq",
      "Uzbekistan",
      "Nicaragua",
      "Venezuela, Boliv Rep of",
      "Zambia",
      "Greece",
      "Czechia",
      "Ireland",
      "Poland",
      "Madagascar",
      "Germany",
      "Tunisia",
      "Guatemala",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Nepal",
      "Denmark",
      "Hungary",
      "Armenia",
      "Solomon Islands",
      "Zimbabwe",
      "Kenya",
      "Ukraine",
      "Tanzania, United Rep. of",
      "Belarus",
      "Panama",
      "Israel",
      "Afghanistan",
      "El Salvador",
      "Paraguay",
      "Croatia",
      "Malawi",
      "Sudan",
      "Papua New Guinea",
      "Kiribati",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Sweden",
      "Portugal",
      "Finland",
      "Bolivia (Plurinat.State)",
      "Timor-Leste",
      "Burundi",
      "Lesotho",
      "Haiti",
      "Brunei Darussalam",
      "French Polynesia",
      "Belize",
      "Syrian Arab Republic",
      "Lebanon",
      "Algeria",
      "Kyrgyzstan",
      "Jordan",
      "Dominican Republic",
      "Kazakhstan",
      "Fiji",
      "C�te d'Ivoire",
      "R�union",
      "Bulgaria",
      "US Virgin Islands",
      "Iceland",
      "Latvia",
      "Slovenia",
      "Singapore"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Southern Europe",
      "Western Africa",
      "Northern America",
      "Central America",
      "Eastern Africa",
      "Western Asia",
      "Australia and New Zealand",
      "Eastern Europe",
      "Western Europe",
      "Central Asia",
      "Caribbean",
      "Melanesia",
      "Micronesia",
      "Middle Africa",
      "Southern Africa",
      "Polynesia"
    ]
  },
  {
    "key": "Captive propagated",
    "value": 621,
    "specie": [
      "Laminaria japonica",
      "Eucheuma spp",
      "Ctenopharyngodon idellus",
      "Crassostrea spp",
      "Ruditapes philippinarum",
      "Hypophthalmichthys molitrix",
      "Hypophthalmichthys nobilis",
      "Gracilaria spp",
      "Cyprinus carpio",
      "Carassius spp",
      "Catla catla",
      "Pectinidae",
      "Porphyra spp",
      "Undaria pinnatifida",
      "Kappaphycus alvarezii",
      "Pangasius spp",
      "Salmo salar",
      "Chanos chanos",
      "Oreochromis niloticus",
      "Procambarus clarkii",
      "Penaeus vannamei",
      "Labeo rohita",
      "Mytilidae",
      "Sinonovacula constricta",
      "Clarias spp",
      "Osteichthyes",
      "Megalobrama amblycephala",
      "Eriocheir sinensis",
      "Mollusca",
      "Mylopharyngodon piceus",
      "Algae",
      "Porphyra tenera",
      "Pangasianodon hypophthalmus",
      "Channa argus",
      "Pelteobagrus fulvidraco",
      "Micropterus salmoides",
      "Cyprinidae",
      "Oreochromis aureus x O. niloticus",
      "Misgurnus anguillicaudatus",
      "Silurus asotus",
      "Monopterus albus",
      "Anadara granosa",
      "Mytilus chilensis",
      "Siniperca chuatsi",
      "Oreochromis (=Tilapia) spp",
      "Trionyx sinensis",
      "Crassostrea gigas",
      "Penaeus monodon",
      "Rapana spp",
      "Macrobrachium nipponense",
      "Ictalurus punctatus",
      "Apostichopus japonicus",
      "Anguilla japonica",
      "Cirrhinus mrigala",
      "Sargassum fusiforme",
      "Mugilidae",
      "Larimichthys croceus",
      "Oncorhynchus mykiss",
      "Oncorhynchus kisutch",
      "Lateolabrax japonicus",
      "Clarias gariepinus",
      "Scylla paramamosain",
      "Haliotis spp",
      "Osphronemus goramy",
      "Seriola quinqueradiata",
      "Macrobrachium rosenbergii",
      "Patinopecten yessoensis",
      "Epinephelus spp",
      "Trachinotus blochii",
      "Portunus spp",
      "Crassostrea virginica",
      "Eucheuma denticulatum",
      "Colossoma macropomum",
      "Clarias gariepinus x C. macrocephalus",
      "Dicentrarchus labrax",
      "Perna canaliculus",
      "Penaeus spp",
      "Cipangopaludina chinensis",
      "Siluroidei",
      "Rana spp",
      "Perna viridis",
      "Acipenseridae",
      "Rhopilema spp",
      "Piaractus brachypomus",
      "Sparidae",
      "Mytilus coruscus",
      "Spirulina spp",
      "Metapenaeus spp",
      "Anodonta cygnea",
      "Sciaenops ocellatus",
      "Palaemonidae",
      "Scylla serrata",
      "Mytilus galloprovincialis",
      "Pagrus auratus",
      "Bivalvia",
      "Sparus aurata",
      "Bothidae",
      "Mytilus edulis",
      "Penaeus japonicus",
      "Testudinata",
      "Psetta maxima",
      "Invertebrata",
      "Rachycentron canadum",
      "Channa striata",
      "Anabas testudineus",
      "Barbonymus gonionotus",
      "Paralichthys olivaceus",
      "Oreochromis mossambicus",
      "Penaeus chinensis",
      "P. mesopotamicus x C. macropomum",
      "Channa micropeltes",
      "Osteochilus hasselti",
      "Labeo calbasu",
      "Seriola spp",
      "Argyrosomus regius",
      "Takifugu rubripes",
      "Mercenaria mercenaria",
      "Crassostrea iredalei",
      "Sebastes schlegeli",
      "Corbicula fluminea",
      "Leiocassis longirostris",
      "Protosalanx hyalocranius",
      "Pangasius pangasius",
      "Penaeus merguiensis",
      "Ascidiacea",
      "Salmonidae",
      "Perna perna",
      "Atrina spp",
      "Lates niloticus",
      "Thunnus orientalis",
      "Scylla olivacea",
      "Brachyura",
      "Pleuronectidae",
      "Piaractus mesopotamicus",
      "Trichogaster pectoralis",
      "Hypomesus olidus",
      "Argopecten purpuratus",
      "Salmo spp",
      "Eleutheronema tetradactylum",
      "Channa spp",
      "Strongylocentrotus spp",
      "Heteropneustes fossilis",
      "Clarias batrachus",
      "Thunnus maccoyii",
      "Papyrocranus afer",
      "Lutjanus argentimaculatus",
      "Lates calcarifer",
      "Pagrus major",
      "Gymnarchus niloticus",
      "C. macropomum x P. brachypomus",
      "Lutjanus johnii",
      "Takifugu obscurus",
      "Capsosiphon fulvescens",
      "Monostroma nitidum",
      "Helostoma temminckii",
      "Puntius spp",
      "Cirrhinus microlepis",
      "Heterotis niloticus",
      "Hemibagrus nemurus",
      "Systomus sarana",
      "Oreochromis shiranus",
      "Ostreidae",
      "Plecoglossus altivelis",
      "Brycon spp",
      "Probarbus jullieni",
      "Leptobarbus hoeveni",
      "Arapaima gigas",
      "Oreochromis andersonii",
      "Crassostrea madrasensis",
      "Osteobrama belangeri",
      "Cirrhinus molitorella",
      "Codium fragile",
      "Leporinus spp",
      "Enteromorpha clathrata",
      "Brycon amazonicus",
      "Prochilodus spp",
      "Ruditapes decussatus",
      "Tilapia rendalli",
      "Prochilodus reticulatus",
      "Anguilla anguilla",
      "Rutilus rutilus",
      "Crassostrea corteziensis",
      "Oncorhynchus tshawytscha",
      "Oreochromis aureus",
      "Penaeus stylirostris",
      "Pinctada margaritifera",
      "Thunnus thynnus",
      "Oreochromis macrochir",
      "Salmo trutta",
      "Prochilodus nigricans",
      "Tinca tinca",
      "Hoplias spp",
      "Oxyeleotris marmorata",
      "Carassius carassius",
      "Lutjanus guttatus",
      "Astyanax fasciatus",
      "Salmonoidei",
      "Abramis brama",
      "Rana catesbeiana",
      "Holothuroidea",
      "Panulirus spp",
      "Silurus glanis",
      "Haematococcus pluvialis",
      "Holothuria scabra",
      "Cerastoderma edule",
      "Ostrea edulis",
      "Chlorella vulgaris",
      "Salvelinus alpinus",
      "Astacidae, Cambaridae",
      "Mugil cephalus",
      "Cromileptes altivelis",
      "Meretrix lusoria"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Freshwater fishes",
      "Molluscs",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes",
      "Miscellaneous aquatic animal products"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Myanmar",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Brazil",
      "Thailand",
      "Spain",
      "Malaysia",
      "United Kingdom",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "United States of America",
      "Mexico",
      "Zanzibar",
      "Turkey",
      "New Zealand",
      "Faroe Islands",
      "Canada",
      "Russian Federation",
      "Italy",
      "Cambodia",
      "Lao People's Dem. Rep.",
      "France",
      "Peru",
      "Ghana",
      "Netherlands",
      "Australia",
      "Taiwan Province of China",
      "Colombia",
      "Pakistan",
      "Saudi Arabia",
      "Uganda",
      "Honduras",
      "Iraq",
      "Uzbekistan",
      "Nicaragua",
      "Venezuela, Boliv Rep of",
      "Zambia",
      "Greece",
      "Czechia",
      "Ireland",
      "Poland",
      "Madagascar",
      "Germany",
      "Tunisia",
      "Guatemala",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Nepal",
      "Denmark",
      "Hungary",
      "Armenia",
      "Solomon Islands",
      "Zimbabwe",
      "Kenya",
      "Ukraine",
      "Tanzania, United Rep. of",
      "Belarus",
      "Panama",
      "Israel",
      "Afghanistan",
      "El Salvador",
      "Paraguay",
      "Croatia",
      "Malawi",
      "Sudan",
      "Papua New Guinea",
      "Kiribati",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Sweden",
      "Portugal",
      "Finland",
      "Bolivia (Plurinat.State)",
      "Timor-Leste",
      "Burundi",
      "Lesotho",
      "Haiti",
      "Brunei Darussalam",
      "French Polynesia",
      "Belize",
      "Syrian Arab Republic",
      "Lebanon",
      "Algeria",
      "Kyrgyzstan",
      "Jordan",
      "Dominican Republic",
      "Kazakhstan",
      "Fiji",
      "C�te d'Ivoire",
      "R�union",
      "Bulgaria",
      "US Virgin Islands",
      "Iceland",
      "Latvia",
      "Slovenia",
      "Singapore"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Southern Europe",
      "Western Africa",
      "Northern America",
      "Central America",
      "Eastern Africa",
      "Western Asia",
      "Australia and New Zealand",
      "Eastern Europe",
      "Western Europe",
      "Central Asia",
      "Caribbean",
      "Melanesia",
      "Micronesia",
      "Middle Africa",
      "Southern Africa",
      "Polynesia"
    ]
  }
];
