module.exports = [{
        "key": "Hybrids",
        "value": 34,
        "taxonomy": ["Aquatic plants", "Freshwater fishes", "Crustaceans"],
        "specie": ["Algae"],
        "ftype": ["Strains", "Captive propagated"],
        "country": [
            "China",
            "India",
            "Viet Nam",
            "Indonesia",
            "Egypt",
            "Bangladesh",
            "Myanmar",
            "Brazil",
            "TBD",
            "Thailand",
            "Philippines",
            "Nigeria",
            "United States of America",
            "Iran (Islamic Rep. of)",
            "Uganda",
            "Russian Federation",
            "Cambodia",
            "Lao People's Dem. Rep.",
            "Mexico",
            "Ghana",
            "Taiwan Province of China",
            "Colombia",
            "Pakistan",
            "Malaysia",
            "Honduras",
            "Iraq",
            "Sri Lanka",
            "Uzbekistan",
            "Ecuador",
            "Zambia",
            "Czechia",
            "Poland",
            "Cuba",
            "Costa Rica",
            "Nepal",
            "Hungary",
            "Zimbabwe",
            "Kenya",
            "Guatemala",
            "Ukraine",
            "Tanzania, United Rep. of",
            "Belarus",
            "Saudi Arabia",
            "Israel",
            "Afghanistan",
            "El Salvador",
            "Paraguay",
            "Malawi",
            "Korea, Republic of",
            "Sudan",
            "Germany",
            "Romania",
            "Moldova, Republic of",
            "Bulgaria",
            "France",
            "Korea, Dem. People's Rep",
            "Serbia",
            "Venezuela, Boliv Rep of",
            "Madagascar",
            "Mali",
            "Rwanda",
            "Congo, Dem. Rep. of the",
            "Peru",
            "Japan",
            "C�te d'Ivoire",
            "Lithuania",
            "Netherlands",
            "Benin",
            "Croatia",
            "Argentina",
            "Mozambique",
            "Burundi",
            "Canada",
            "Angola",
            "Haiti",
            "Armenia",
            "Papua New Guinea",
            "Cameroon",
            "Jamaica",
            "Syrian Arab Republic",
            "Slovakia",
            "Australia",
            "Bolivia (Plurinat.State)",
            "Algeria",
            "Kyrgyzstan",
            "China, Hong Kong SAR",
            "Austria",
            "Latvia",
            "Jordan",
            "Italy",
            "Dominican Republic",
            "Kazakhstan",
            "Bosnia and Herzegovina",
            "Tunisia",
            "Guyana",
            "Switzerland",
            "Morocco",
            "Burkina Faso",
            "Denmark",
            "Senegal",
            "North Macedonia",
            "Turkey",
            "Niger",
            "South Africa",
            "Tajikistan",
            "Azerbaijan",
            "Fiji",
            "Congo",
            "Georgia",
            "Chad",
            "Guinea",
            "United Kingdom",
            "Kuwait",
            "Estonia",
            "Singapore",
            "Finland",
            "Ethiopia",
            "Slovenia",
            "Togo",
            "Eswatini",
            "Central African Republic",
            "Sierra Leone",
            "Oman",
            "Suriname",
            "Belgium",
            "Guam",
            "Belize",
            "Panama",
            "Bhutan",
            "Gabon",
            "Spain",
            "Guinea-Bissau",
            "Liberia",
            "Greece",
            "Timor-Leste",
            "Palestine",
            "Barbados",
            "Namibia",
            "Turkmenistan",
            "American Samoa",
            "South Sudan",
            "United Arab Emirates",
            "Northern Mariana Is.",
            "Brunei Darussalam",
            "Botswana",
            "Lebanon",
            "Trinidad and Tobago",
            "Gambia",
            "Nicaragua",
            "Antigua and Barbuda",
            "Qatar",
            "Vanuatu",
            "Libya",
            "Samoa",
            "Saint Lucia",
            "Equatorial Guinea",
            "Puerto Rico",
            "Dominica",
            "R�union",
            "US Virgin Islands",
            "Mauritius",
            "Solomon Islands",
            "Guadeloupe",
            "Lesotho",
            "French Guiana",
            "Bahamas",
            "Cook Islands",
            "Saint Kitts and Nevis",
            "Martinique",
            "Uruguay",
            "Sudan (former)",
            "Albania",
            "French Polynesia",
            "Czechoslovakia",
            "Montenegro",
            "Serbia and Montenegro",
            "Sweden",
            "Un. Sov. Soc. Rep.",
            "Yugoslavia SFR",
            "Ireland",
            "Chile",
            "Kiribati",
            "Portugal",
            "Grenada",
            "Eritrea",
            "Malta",
            "Aruba",
            "Cyprus",
            "Iceland",
            "Mayotte"
        ],
        "continent": [
          "Asia",
          "Europe",
          "Africa",
          "Americas",
          "Oceania"
        ]
    },
    {
        "key": "Introgressed",
        "value": 56,
        "taxonomy": ["Aquatic plants", "Freshwater fishes", "Crustaceans"],
        "specie": ["Osteichthyes"],
        "ftype": ["Strains", "Varieties"],
        "country": [
            "China",
            "Indonesia",
            "Egypt",
            "Japan",
            "Bangladesh",
            "Turkey",
            "India",
            "Greece",
            "Korea, Republic of",
            "Taiwan Province of China",
            "Tunisia",
            "Spain",
            "Iran (Islamic Rep. of)",
            "Viet Nam",
            "Australia",
            "Malaysia",
            "Mexico",
            "Croatia",
            "Cyprus",
            "Italy",
            "Malta",
            "Albania",
            "Portugal",
            "Saudi Arabia",
            "Israel",
            "United Arab Emirates",
            "Panama",
            "Norway",
            "Thailand",
            "Mauritius",
            "France",
            "United States of America",
            "China, Hong Kong SAR",
            "Costa Rica",
            "Palestine",
            "Philippines",
            "Dominican Republic",
            "Iceland",
            "Singapore",
            "Ecuador",
            "Cambodia",
            "Algeria",
            "Kuwait",
            "Morocco",
            "Netherlands",
            "Bosnia and Herzegovina",
            "Slovenia",
            "Korea, Dem. People's Rep",
            "United Kingdom",
            "Brunei Darussalam",
            "Montenegro",
            "Martinique",
            "French Polynesia",
            "Brazil",
            "Georgia",
            "Guadeloupe",
            "Myanmar",
            "New Caledonia",
            "Marshall Islands",
            "Peru",
            "El Salvador",
            "Channel Islands",
            "Canada",
            "Libya",
            "Denmark",
            "Russian Federation",
            "Venezuela, Boliv Rep of",
            "Chile",
            "Germany",
            "Bahamas",
            "Belize",
            "Bonaire/S.Eustatius/Saba",
            "Colombia",
            "Mayotte",
            "Puerto Rico",
            "R�union",
            "Ukraine",
            "Oman",
            "Yugoslavia SFR",
            "Un. Sov. Soc. Rep.",
            "Fiji",
            "Guyana",
            "Bahrain",
            "Mozambique",
            "South Africa",
            "Argentina",
            "Romania",
            "Azerbaijan",
            "Guam",
            "Iraq",
            "Nigeria",
            "Ireland",
            "Qatar",
            "TBD"
        ],
        "continent": [
          "Asia",
          "Europe",
          "Africa",
          "Americas",
          "Oceania"
        ]
    },
    {
        "key": "Crossbred",
        "value": 45,
        "taxonomy": ["Freshwater fishes"],
        "specie": ["Osteichthyes"],
        "ftype": ["Varieties"],
        "country": [
            "Norway",
            "Indonesia",
            "Chile",
            "Philippines",
            "China",
            "United Kingdom",
            "Iran (Islamic Rep. of)",
            "Turkey",
            "Faroe Islands",
            "Canada",
            "Peru",
            "Australia",
            "Italy",
            "Russian Federation",
            "Taiwan Province of China",
            "France",
            "Malaysia",
            "Japan",
            "Denmark",
            "United States of America",
            "Ireland",
            "Spain",
            "Thailand",
            "Poland",
            "New Zealand",
            "Finland",
            "Iceland",
            "Korea, Republic of",
            "Armenia",
            "Mexico",
            "Sweden",
            "Germany",
            "Colombia",
            "Ecuador",
            "Saudi Arabia",
            "Bulgaria",
            "Bosnia and Herzegovina",
            "Netherlands",
            "Singapore",
            "Brazil",
            "Greece",
            "Romania",
            "Bolivia (Plurinat.State)",
            "South Africa",
            "Argentina",
            "Viet Nam",
            "Austria",
            "Switzerland",
            "Lesotho",
            "North Macedonia",
            "Slovakia",
            "Lebanon",
            "Serbia",
            "Costa Rica",
            "Cambodia",
            "India",
            "Kyrgyzstan",
            "Slovenia",
            "Estonia",
            "Montenegro",
            "Portugal",
            "Kenya",
            "Albania",
            "Kazakhstan",
            "Belarus",
            "Czechia",
            "Myanmar",
            "Israel",
            "Croatia",
            "Ukraine",
            "Tanzania, United Rep. of",
            "Nepal",
            "Azerbaijan",
            "Morocco",
            "United Arab Emirates",
            "Sri Lanka",
            "Brunei Darussalam",
            "Georgia",
            "Afghanistan",
            "Papua New Guinea",
            "Uzbekistan",
            "Guatemala",
            "Lithuania",
            "Hungary",
            "Latvia",
            "Venezuela, Boliv Rep of",
            "Zimbabwe",
            "Malawi",
            "Korea, Dem. People's Rep",
            "Cyprus",
            "Uruguay",
            "Guam",
            "Bhutan",
            "Panama",
            "Palau",
            "Tajikistan",
            "Timor-Leste",
            "R�union",
            "Tunisia",
            "Palestine",
            "Tuvalu",
            "Kuwait",
            "Kiribati",
            "Ethiopia",
            "Zanzibar",
            "Northern Mariana Is.",
            "Egypt",
            "Nauru",
            "Dominican Republic",
            "Bahrain",
            "China, Hong Kong SAR",
            "French Polynesia",
            "Vanuatu",
            "Belgium",
            "Un. Sov. Soc. Rep.",
            "Algeria",
            "Malta",
            "Serbia and Montenegro",
            "Yugoslavia SFR",
            "Cook Islands",
            "Micronesia, Fed.States of",
            "Tonga",
            "Madagascar",
            "Moldova, Republic of",
            "Czechoslovakia"
        ],
        "continent": [
          "Asia",
          "Europe",
          "Africa",
          "Americas",
          "Oceania"
        ]
    },
    {
        "key": "Polyploid",
        "value": 76,
        "taxonomy": ["Aquatic plants", "Crustaceans"],
        "specie": ["Algae"],
        "ftype": ["Captive propagated", "Strains"],
        "country": [
            "China",
            "Thailand",
            "Chile",
            "Korea, Republic of",
            "Viet Nam",
            "Spain",
            "Japan",
            "United States of America",
            "New Zealand",
            "Italy",
            "Korea, Dem. People's Rep",
            "France",
            "Netherlands",
            "Taiwan Province of China",
            "Indonesia",
            "Canada",
            "Philippines",
            "Greece",
            "Brazil",
            "Germany",
            "Ireland",
            "United Kingdom",
            "Peru",
            "Malaysia",
            "India",
            "Mexico",
            "Russian Federation",
            "Australia",
            "Cambodia",
            "Bulgaria",
            "Denmark",
            "Norway",
            "Portugal",
            "Sweden",
            "South Africa",
            "Channel Islands",
            "Cuba",
            "China, Hong Kong SAR",
            "Croatia",
            "Slovenia",
            "Turkey",
            "Albania",
            "Morocco",
            "Namibia",
            "Singapore",
            "Senegal",
            "Montenegro",
            "Tunisia",
            "St. Pierre and Miquelon",
            "Iceland",
            "Gambia",
            "Costa Rica",
            "Argentina",
            "El Salvador",
            "Sri Lanka",
            "Ecuador",
            "Cook Islands",
            "United Arab Emirates",
            "Venezuela, Boliv Rep of",
            "Palau",
            "Mauritius",
            "Algeria",
            "Papua New Guinea",
            "Turks and Caicos Is.",
            "Dominican Republic",
            "Fiji",
            "Guatemala",
            "Samoa",
            "Tonga",
            "Falkland Is.(Malvinas)",
            "Micronesia, Fed.States of",
            "Colombia",
            "Israel",
            "Bosnia and Herzegovina",
            "Yugoslavia SFR",
            "Jamaica",
            "Puerto Rico",
            "Romania",
            "Serbia and Montenegro",
            "Ukraine",
            "Un. Sov. Soc. Rep.",
            "New Caledonia",
            "French Polynesia",
            "Netherlands Antilles",
            "TBD"
        ],
        "continent": [
          "Asia",
          "Europe",
          "Africa",
          "Americas",
          "Oceania"
        ]
    },
    {
        "key": "Monosex",
        "value": 12,
        "taxonomy": ["Aquatic plants", "Freshwater fishes", "Crustaceans"],
        "specie": ["Algae"],
        "ftype": ["Strains", "Varieties"],
        "country": [
            "China",
            "India",
            "Indonesia",
            "Viet Nam",
            "Ecuador",
            "Thailand",
            "Mexico",
            "Bangladesh",
            "United States of America",
            "Brazil",
            "Myanmar",
            "Philippines",
            "Saudi Arabia",
            "Iran (Islamic Rep. of)",
            "Honduras",
            "Malaysia",
            "Peru",
            "Nicaragua",
            "Venezuela, Boliv Rep of",
            "Guatemala",
            "Panama",
            "Taiwan Province of China",
            "Cuba",
            "Madagascar",
            "Korea, Republic of",
            "Sri Lanka",
            "Australia",
            "TBD",
            "Costa Rica",
            "Colombia",
            "New Caledonia",
            "Japan",
            "Brunei Darussalam",
            "El Salvador",
            "Belize",
            "Cambodia",
            "Tanzania, United Rep. of",
            "Dominican Republic",
            "Guyana",
            "United Arab Emirates",
            "Spain",
            "Pakistan",
            "Egypt",
            "Nigeria",
            "French Polynesia",
            "France",
            "Singapore",
            "Suriname",
            "Cyprus",
            "Northern Mariana Is.",
            "Norway",
            "Armenia",
            "Russian Federation",
            "Portugal",
            "Fiji",
            "Bulgaria",
            "Puerto Rico",
            "Greece",
            "Ghana",
            "Italy",
            "Guam",
            "Lebanon",
            "Vanuatu",
            "Martinique",
            "South Africa",
            "Bahamas",
            "Algeria",
            "Saint Lucia",
            "Guadeloupe",
            "Tunisia",
            "Romania",
            "Sweden",
            "Dominica",
            "Mauritius",
            "Timor-Leste",
            "Estonia",
            "Poland",
            "Barbados",
            "Palau",
            "Samoa",
            "Ukraine",
            "Moldova, Republic of",
            "Austria",
            "Latvia",
            "Argentina",
            "French Guiana",
            "Grenada",
            "Israel",
            "Jamaica",
            "Malawi",
            "Paraguay",
            "R�union",
            "Senegal",
            "Solomon Islands",
            "Trinidad and Tobago",
            "Uganda",
            "Zimbabwe",
            "Cook Islands",
            "Mozambique",
            "Papua New Guinea",
            "Seychelles",
            "Oman",
            "Yemen",
            "Albania",
            "Turks and Caicos Is.",
            "Turkey",
            "Denmark",
            "Eritrea",
            "Gambia",
            "Kenya",
            "Morocco",
            "Uruguay",
            "Eswatini",
            "Zambia",
            "United Kingdom",
            "Saint Kitts and Nevis"
        ],
        "continent": [
          "Asia",
          "Europe",
          "Africa",
          "Americas",
          "Oceania"
        ]
    },
    {
        "key": "Transgenic",
        "value": 123,
        "taxonomy": ["Aquatic plants", "Freshwater fishes", "Crustaceans"],
        "specie": ["Algae"],
        "ftype": ["Wild sourced", "Captive propagated"],
        "country": [
            "China",
            "Indonesia",
            "Philippines",
            "Korea, Republic of",
            "Korea, Dem. People's Rep",
            "Japan",
            "Malaysia",
            "TBD",
            "Zanzibar",
            "Madagascar",
            "Chile",
            "Solomon Islands",
            "Viet Nam",
            "Tanzania, United Rep. of",
            "Papua New Guinea",
            "Kiribati",
            "Cambodia",
            "India",
            "Russian Federation",
            "Timor-Leste",
            "South Africa",
            "Sri Lanka",
            "Taiwan Province of China",
            "Fiji",
            "Kenya",
            "Myanmar",
            "Greece",
            "Norway",
            "Namibia",
            "Morocco",
            "Tunisia",
            "Ireland",
            "Portugal",
            "Mexico",
            "Tonga",
            "Chad",
            "Grenada",
            "Saint Lucia",
            "Denmark",
            "Ecuador",
            "Spain",
            "Bulgaria",
            "Belize",
            "Peru",
            "Senegal",
            "Saint Vincent/Grenadines",
            "Saint Kitts and Nevis",
            "Burkina Faso",
            "Uruguay",
            "Un. Sov. Soc. Rep.",
            "Cook Islands",
            "Brazil",
            "Mozambique",
            "Venezuela, Boliv Rep of",
            "Micronesia, Fed.States of",
            "Italy",
            "France",
            "Central African Republic"
        ],
        "continent": [
          "Asia",
          "Europe",
          "Africa",
          "Americas",
          "Oceania"
        ]
    },
    {
        "key": "Gene edited",
        "value": 64,
        "taxonomy": ["Freshwater fishes"],
        "specie": ["Osteichthyes"],
        "ftype": ["Captive propagated"],
        "country": [
            "China",
            "Japan",
            "Viet Nam",
            "Russian Federation",
            "Taiwan Province of China",
            "Thailand",
            "Singapore",
            "Malaysia",
            "Indonesia",
            "Brazil",
            "Mexico",
            "Myanmar",
            "Korea, Republic of",
            "Korea, Dem. People's Rep",
            "Madagascar",
            "Cambodia",
            "Lao People's Dem. Rep.",
            "Turkey",
            "Sri Lanka",
            "Argentina",
            "France",
            "Ireland",
            "Zanzibar",
            "Spain",
            "Uruguay",
            "Belgium",
            "Netherlands",
            "Bulgaria",
            "Greece",
            "Romania",
            "R�union",
            "South Africa",
            "Saudi Arabia",
            ""
        ],
        "continent": [
          "Asia",
          "Europe",
          "Africa",
          "Americas",
          "Oceania"
        ]
    }
]
