module.exports = [
  {
    "key": "Hybrids",
    "value": 298,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Central Africa"
    ],
    "specie": [
      "Laminaria japonica",
      "Eucheuma spp",
      "Ruditapes philippinarum",
      "Hypophthalmichthys molitrix",
      "Gracilaria spp",
      "Catla catla",
      "Pectinidae",
      "Porphyra spp",
      "Undaria pinnatifida",
      "Kappaphycus alvarezii",
      "Pangasius spp",
      "Salmo salar",
      "Chanos chanos",
      "Oreochromis niloticus",
      "Procambarus clarkii",
      "Labeo rohita",
      "Mytilidae",
      "Sinonovacula constricta",
      "Clarias spp",
      "Osteichthyes",
      "Megalobrama amblycephala",
      "Eriocheir sinensis",
      "Mollusca",
      "Algae",
      "Cyprinus carpio",
      "Porphyra tenera",
      "Pangasianodon hypophthalmus",
      "Channa argus",
      "Penaeus vannamei",
      "Cyprinidae",
      "Oreochromis aureus x O. niloticus",
      "Misgurnus anguillicaudatus",
      "Silurus asotus",
      "Monopterus albus",
      "Oreochromis (=Tilapia) spp",
      "Trionyx sinensis",
      "Macrobrachium nipponense",
      "Apostichopus japonicus",
      "Mugilidae",
      "Cirrhinus mrigala",
      "Larimichthys croceus",
      "Oncorhynchus mykiss",
      "Oncorhynchus kisutch",
      "Clarias gariepinus",
      "Haliotis spp",
      "Seriola quinqueradiata",
      "Macrobrachium rosenbergii",
      "Patinopecten yessoensis",
      "Penaeus monodon",
      "Epinephelus spp",
      "Trachinotus blochii",
      "Portunus spp",
      "Clarias gariepinus x C. macrocephalus",
      "Dicentrarchus labrax",
      "Siluroidei",
      "Perna viridis",
      "Acipenseridae",
      "Piaractus brachypomus",
      "Spirulina spp",
      "Metapenaeus spp",
      "Anodonta cygnea",
      "Mytilus galloprovincialis",
      "Bivalvia",
      "Bothidae",
      "Crassostrea gigas",
      "Sargassum fusiforme",
      "Penaeus japonicus",
      "Invertebrata",
      "Channa striata",
      "Anabas testudineus",
      "Barbonymus gonionotus",
      "Oreochromis mossambicus",
      "Sparus aurata",
      "Ctenopharyngodon idellus",
      "Osteochilus hasselti",
      "Seriola spp",
      "Mercenaria mercenaria",
      "Corbicula fluminea",
      "Leiocassis longirostris",
      "Anguilla japonica",
      "Protosalanx hyalocranius",
      "Pangasius pangasius",
      "Perna perna",
      "Mytilus edulis",
      "Atrina spp",
      "Thunnus orientalis",
      "Scylla olivacea",
      "Brachyura",
      "Pleuronectidae",
      "Piaractus mesopotamicus",
      "Trichogaster pectoralis",
      "Anadara granosa",
      "Labeo calbasu",
      "Psetta maxima",
      "Heteropneustes fossilis",
      "Papyrocranus afer",
      "Lutjanus argentimaculatus",
      "Helostoma temminckii",
      "Hemibagrus nemurus",
      "Lates calcarifer",
      "Leptobarbus hoeveni",
      "Arapaima gigas",
      "Osteobrama belangeri",
      "Leporinus spp",
      "Brycon amazonicus",
      "Prochilodus spp",
      "Crassostrea spp",
      "Prochilodus reticulatus",
      "Ruditapes decussatus",
      "Anguilla anguilla",
      "Colossoma macropomum",
      "Oncorhynchus tshawytscha",
      "Ostreidae",
      "Oreochromis aureus",
      "Thunnus thynnus",
      "Oreochromis macrochir",
      "Channa spp",
      "Carassius carassius",
      "Lutjanus guttatus",
      "Scylla serrata",
      "Meretrix lusoria"
    ]
  },
  {
    "key": "Introgressed",
    "value": 297,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Central Africa"
    ],
    "specie": [
      "Laminaria japonica",
      "Eucheuma spp",
      "Ruditapes philippinarum",
      "Hypophthalmichthys molitrix",
      "Gracilaria spp",
      "Catla catla",
      "Pectinidae",
      "Porphyra spp",
      "Undaria pinnatifida",
      "Kappaphycus alvarezii",
      "Pangasius spp",
      "Salmo salar",
      "Chanos chanos",
      "Oreochromis niloticus",
      "Procambarus clarkii",
      "Labeo rohita",
      "Mytilidae",
      "Sinonovacula constricta",
      "Osteichthyes",
      "Megalobrama amblycephala",
      "Eriocheir sinensis",
      "Mollusca",
      "Algae",
      "Cyprinus carpio",
      "Porphyra tenera",
      "Pangasianodon hypophthalmus",
      "Channa argus",
      "Penaeus vannamei",
      "Cyprinidae",
      "Oreochromis aureus x O. niloticus",
      "Misgurnus anguillicaudatus",
      "Silurus asotus",
      "Monopterus albus",
      "Oreochromis (=Tilapia) spp",
      "Trionyx sinensis",
      "Macrobrachium nipponense",
      "Apostichopus japonicus",
      "Mugilidae",
      "Cirrhinus mrigala",
      "Larimichthys croceus",
      "Oncorhynchus mykiss",
      "Oncorhynchus kisutch",
      "Clarias gariepinus",
      "Haliotis spp",
      "Seriola quinqueradiata",
      "Macrobrachium rosenbergii",
      "Patinopecten yessoensis",
      "Penaeus monodon",
      "Epinephelus spp",
      "Trachinotus blochii",
      "Portunus spp",
      "Clarias gariepinus x C. macrocephalus",
      "Dicentrarchus labrax",
      "Siluroidei",
      "Perna viridis",
      "Acipenseridae",
      "Piaractus brachypomus",
      "Spirulina spp",
      "Metapenaeus spp",
      "Anodonta cygnea",
      "Mytilus galloprovincialis",
      "Bivalvia",
      "Bothidae",
      "Crassostrea gigas",
      "Sargassum fusiforme",
      "Penaeus japonicus",
      "Invertebrata",
      "Channa striata",
      "Anabas testudineus",
      "Barbonymus gonionotus",
      "Oreochromis mossambicus",
      "Sparus aurata",
      "Clarias spp",
      "Ctenopharyngodon idellus",
      "Osteochilus hasselti",
      "Seriola spp",
      "Mercenaria mercenaria",
      "Corbicula fluminea",
      "Leiocassis longirostris",
      "Anguilla japonica",
      "Protosalanx hyalocranius",
      "Pangasius pangasius",
      "Perna perna",
      "Mytilus edulis",
      "Atrina spp",
      "Thunnus orientalis",
      "Scylla olivacea",
      "Brachyura",
      "Pleuronectidae",
      "Piaractus mesopotamicus",
      "Trichogaster pectoralis",
      "Anadara granosa",
      "Labeo calbasu",
      "Psetta maxima",
      "Heteropneustes fossilis",
      "Papyrocranus afer",
      "Lutjanus argentimaculatus",
      "Helostoma temminckii",
      "Hemibagrus nemurus",
      "Lates calcarifer",
      "Leptobarbus hoeveni",
      "Arapaima gigas",
      "Osteobrama belangeri",
      "Leporinus spp",
      "Brycon amazonicus",
      "Prochilodus spp",
      "Crassostrea spp",
      "Prochilodus reticulatus",
      "Ruditapes decussatus",
      "Anguilla anguilla",
      "Colossoma macropomum",
      "Oncorhynchus tshawytscha",
      "Ostreidae",
      "Oreochromis aureus",
      "Thunnus thynnus",
      "Oreochromis macrochir",
      "Channa spp",
      "Carassius carassius",
      "Lutjanus guttatus",
      "Scylla serrata",
      "Meretrix lusoria"
    ]
  },
  {
    "key": "Crossbred",
    "value": 297,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Central Africa"
    ],
    "specie": [
      "Laminaria japonica",
      "Eucheuma spp",
      "Ruditapes philippinarum",
      "Hypophthalmichthys molitrix",
      "Gracilaria spp",
      "Catla catla",
      "Pectinidae",
      "Porphyra spp",
      "Undaria pinnatifida",
      "Kappaphycus alvarezii",
      "Pangasius spp",
      "Salmo salar",
      "Chanos chanos",
      "Oreochromis niloticus",
      "Procambarus clarkii",
      "Mytilidae",
      "Sinonovacula constricta",
      "Clarias spp",
      "Osteichthyes",
      "Megalobrama amblycephala",
      "Eriocheir sinensis",
      "Mollusca",
      "Algae",
      "Cyprinus carpio",
      "Porphyra tenera",
      "Pangasianodon hypophthalmus",
      "Channa argus",
      "Penaeus vannamei",
      "Cyprinidae",
      "Oreochromis aureus x O. niloticus",
      "Misgurnus anguillicaudatus",
      "Silurus asotus",
      "Monopterus albus",
      "Oreochromis (=Tilapia) spp",
      "Trionyx sinensis",
      "Labeo rohita",
      "Macrobrachium nipponense",
      "Apostichopus japonicus",
      "Mugilidae",
      "Cirrhinus mrigala",
      "Larimichthys croceus",
      "Oncorhynchus mykiss",
      "Oncorhynchus kisutch",
      "Clarias gariepinus",
      "Haliotis spp",
      "Seriola quinqueradiata",
      "Macrobrachium rosenbergii",
      "Patinopecten yessoensis",
      "Penaeus monodon",
      "Epinephelus spp",
      "Trachinotus blochii",
      "Portunus spp",
      "Clarias gariepinus x C. macrocephalus",
      "Dicentrarchus labrax",
      "Siluroidei",
      "Perna viridis",
      "Acipenseridae",
      "Piaractus brachypomus",
      "Spirulina spp",
      "Metapenaeus spp",
      "Anodonta cygnea",
      "Mytilus galloprovincialis",
      "Bivalvia",
      "Bothidae",
      "Crassostrea gigas",
      "Sargassum fusiforme",
      "Penaeus japonicus",
      "Invertebrata",
      "Channa striata",
      "Anabas testudineus",
      "Barbonymus gonionotus",
      "Oreochromis mossambicus",
      "Sparus aurata",
      "Ctenopharyngodon idellus",
      "Osteochilus hasselti",
      "Seriola spp",
      "Mercenaria mercenaria",
      "Corbicula fluminea",
      "Leiocassis longirostris",
      "Anguilla japonica",
      "Protosalanx hyalocranius",
      "Pangasius pangasius",
      "Perna perna",
      "Mytilus edulis",
      "Atrina spp",
      "Thunnus orientalis",
      "Scylla olivacea",
      "Brachyura",
      "Pleuronectidae",
      "Piaractus mesopotamicus",
      "Trichogaster pectoralis",
      "Anadara granosa",
      "Labeo calbasu",
      "Psetta maxima",
      "Heteropneustes fossilis",
      "Papyrocranus afer",
      "Lutjanus argentimaculatus",
      "Helostoma temminckii",
      "Hemibagrus nemurus",
      "Lates calcarifer",
      "Leptobarbus hoeveni",
      "Arapaima gigas",
      "Osteobrama belangeri",
      "Leporinus spp",
      "Brycon amazonicus",
      "Prochilodus spp",
      "Crassostrea spp",
      "Prochilodus reticulatus",
      "Ruditapes decussatus",
      "Anguilla anguilla",
      "Colossoma macropomum",
      "Oncorhynchus tshawytscha",
      "Ostreidae",
      "Oreochromis aureus",
      "Thunnus thynnus",
      "Oreochromis macrochir",
      "Channa spp",
      "Carassius carassius",
      "Lutjanus guttatus",
      "Scylla serrata",
      "Meretrix lusoria"
    ]
  },
  {
    "key": "Polyploid",
    "value": 297,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Central Africa"
    ],
    "specie": [
      "Laminaria japonica",
      "Eucheuma spp",
      "Ruditapes philippinarum",
      "Hypophthalmichthys molitrix",
      "Gracilaria spp",
      "Catla catla",
      "Pectinidae",
      "Porphyra spp",
      "Undaria pinnatifida",
      "Kappaphycus alvarezii",
      "Pangasius spp",
      "Salmo salar",
      "Chanos chanos",
      "Oreochromis niloticus",
      "Procambarus clarkii",
      "Labeo rohita",
      "Mytilidae",
      "Sinonovacula constricta",
      "Clarias spp",
      "Osteichthyes",
      "Megalobrama amblycephala",
      "Eriocheir sinensis",
      "Mollusca",
      "Algae",
      "Cyprinus carpio",
      "Porphyra tenera",
      "Pangasianodon hypophthalmus",
      "Channa argus",
      "Penaeus vannamei",
      "Cyprinidae",
      "Oreochromis aureus x O. niloticus",
      "Misgurnus anguillicaudatus",
      "Silurus asotus",
      "Monopterus albus",
      "Oreochromis (=Tilapia) spp",
      "Trionyx sinensis",
      "Macrobrachium nipponense",
      "Apostichopus japonicus",
      "Mugilidae",
      "Cirrhinus mrigala",
      "Larimichthys croceus",
      "Oncorhynchus mykiss",
      "Oncorhynchus kisutch",
      "Clarias gariepinus",
      "Haliotis spp",
      "Seriola quinqueradiata",
      "Macrobrachium rosenbergii",
      "Patinopecten yessoensis",
      "Penaeus monodon",
      "Epinephelus spp",
      "Trachinotus blochii",
      "Portunus spp",
      "Clarias gariepinus x C. macrocephalus",
      "Dicentrarchus labrax",
      "Siluroidei",
      "Perna viridis",
      "Acipenseridae",
      "Piaractus brachypomus",
      "Spirulina spp",
      "Metapenaeus spp",
      "Anodonta cygnea",
      "Mytilus galloprovincialis",
      "Bivalvia",
      "Bothidae",
      "Crassostrea gigas",
      "Sargassum fusiforme",
      "Penaeus japonicus",
      "Invertebrata",
      "Channa striata",
      "Anabas testudineus",
      "Barbonymus gonionotus",
      "Oreochromis mossambicus",
      "Sparus aurata",
      "Ctenopharyngodon idellus",
      "Osteochilus hasselti",
      "Seriola spp",
      "Mercenaria mercenaria",
      "Corbicula fluminea",
      "Leiocassis longirostris",
      "Anguilla japonica",
      "Protosalanx hyalocranius",
      "Pangasius pangasius",
      "Perna perna",
      "Mytilus edulis",
      "Atrina spp",
      "Thunnus orientalis",
      "Scylla olivacea",
      "Brachyura",
      "Pleuronectidae",
      "Piaractus mesopotamicus",
      "Trichogaster pectoralis",
      "Anadara granosa",
      "Labeo calbasu",
      "Psetta maxima",
      "Heteropneustes fossilis",
      "Papyrocranus afer",
      "Lutjanus argentimaculatus",
      "Helostoma temminckii",
      "Hemibagrus nemurus",
      "Lates calcarifer",
      "Leptobarbus hoeveni",
      "Arapaima gigas",
      "Osteobrama belangeri",
      "Leporinus spp",
      "Brycon amazonicus",
      "Prochilodus spp",
      "Crassostrea spp",
      "Prochilodus reticulatus",
      "Ruditapes decussatus",
      "Anguilla anguilla",
      "Colossoma macropomum",
      "Oncorhynchus tshawytscha",
      "Ostreidae",
      "Oreochromis aureus",
      "Thunnus thynnus",
      "Oreochromis macrochir",
      "Channa spp",
      "Carassius carassius",
      "Lutjanus guttatus",
      "Scylla serrata",
      "Meretrix lusoria"
    ]
  },
  {
    "key": "Monosex",
    "value": 293,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "Indonesia",
      "China",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Japan",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "South-Eastern Asia",
      "Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Central Africa"
    ],
    "specie": [
      "Eucheuma spp",
      "Ruditapes philippinarum",
      "Hypophthalmichthys molitrix",
      "Catla catla",
      "Pectinidae",
      "Porphyra spp",
      "Undaria pinnatifida",
      "Kappaphycus alvarezii",
      "Pangasius spp",
      "Salmo salar",
      "Chanos chanos",
      "Gracilaria spp",
      "Oreochromis niloticus",
      "Procambarus clarkii",
      "Labeo rohita",
      "Mytilidae",
      "Sinonovacula constricta",
      "Clarias spp",
      "Osteichthyes",
      "Megalobrama amblycephala",
      "Eriocheir sinensis",
      "Mollusca",
      "Laminaria japonica",
      "Cyprinus carpio",
      "Porphyra tenera",
      "Pangasianodon hypophthalmus",
      "Channa argus",
      "Penaeus vannamei",
      "Cyprinidae",
      "Oreochromis aureus x O. niloticus",
      "Misgurnus anguillicaudatus",
      "Silurus asotus",
      "Monopterus albus",
      "Oreochromis (=Tilapia) spp",
      "Trionyx sinensis",
      "Macrobrachium nipponense",
      "Apostichopus japonicus",
      "Mugilidae",
      "Cirrhinus mrigala",
      "Larimichthys croceus",
      "Oncorhynchus mykiss",
      "Oncorhynchus kisutch",
      "Clarias gariepinus",
      "Haliotis spp",
      "Seriola quinqueradiata",
      "Macrobrachium rosenbergii",
      "Patinopecten yessoensis",
      "Penaeus monodon",
      "Epinephelus spp",
      "Trachinotus blochii",
      "Portunus spp",
      "Clarias gariepinus x C. macrocephalus",
      "Dicentrarchus labrax",
      "Siluroidei",
      "Perna viridis",
      "Acipenseridae",
      "Piaractus brachypomus",
      "Spirulina spp",
      "Metapenaeus spp",
      "Anodonta cygnea",
      "Mytilus galloprovincialis",
      "Bivalvia",
      "Bothidae",
      "Crassostrea gigas",
      "Sargassum fusiforme",
      "Penaeus japonicus",
      "Invertebrata",
      "Channa striata",
      "Anabas testudineus",
      "Barbonymus gonionotus",
      "Oreochromis mossambicus",
      "Sparus aurata",
      "Ctenopharyngodon idellus",
      "Osteochilus hasselti",
      "Seriola spp",
      "Mercenaria mercenaria",
      "Corbicula fluminea",
      "Leiocassis longirostris",
      "Anguilla japonica",
      "Protosalanx hyalocranius",
      "Pangasius pangasius",
      "Algae",
      "Perna perna",
      "Mytilus edulis",
      "Atrina spp",
      "Thunnus orientalis",
      "Scylla olivacea",
      "Brachyura",
      "Pleuronectidae",
      "Piaractus mesopotamicus",
      "Trichogaster pectoralis",
      "Anadara granosa",
      "Labeo calbasu",
      "Psetta maxima",
      "Heteropneustes fossilis",
      "Papyrocranus afer",
      "Lutjanus argentimaculatus",
      "Helostoma temminckii",
      "Hemibagrus nemurus",
      "Lates calcarifer",
      "Leptobarbus hoeveni",
      "Arapaima gigas",
      "Osteobrama belangeri",
      "Leporinus spp",
      "Brycon amazonicus",
      "Prochilodus spp",
      "Crassostrea spp",
      "Prochilodus reticulatus",
      "Ruditapes decussatus",
      "Anguilla anguilla",
      "Colossoma macropomum",
      "Oncorhynchus tshawytscha",
      "Ostreidae",
      "Oreochromis aureus",
      "Thunnus thynnus",
      "Oreochromis macrochir",
      "Channa spp",
      "Carassius carassius",
      "Lutjanus guttatus",
      "Scylla serrata",
      "Meretrix lusoria"
    ]
  },
  {
    "key": "Transgenic",
    "value": 291,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "Indonesia",
      "China",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Japan",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ecuador",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "South-Eastern Asia",
      "Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Central Africa"
    ],
    "specie": [
      "Eucheuma spp",
      "Ruditapes philippinarum",
      "Hypophthalmichthys molitrix",
      "Catla catla",
      "Pectinidae",
      "Porphyra spp",
      "Undaria pinnatifida",
      "Kappaphycus alvarezii",
      "Pangasius spp",
      "Salmo salar",
      "Chanos chanos",
      "Gracilaria spp",
      "Oreochromis niloticus",
      "Procambarus clarkii",
      "Labeo rohita",
      "Mytilidae",
      "Sinonovacula constricta",
      "Clarias spp",
      "Osteichthyes",
      "Megalobrama amblycephala",
      "Eriocheir sinensis",
      "Mollusca",
      "Laminaria japonica",
      "Porphyra tenera",
      "Pangasianodon hypophthalmus",
      "Channa argus",
      "Penaeus vannamei",
      "Cyprinidae",
      "Oreochromis aureus x O. niloticus",
      "Misgurnus anguillicaudatus",
      "Silurus asotus",
      "Monopterus albus",
      "Oreochromis (=Tilapia) spp",
      "Trionyx sinensis",
      "Macrobrachium nipponense",
      "Apostichopus japonicus",
      "Mugilidae",
      "Cirrhinus mrigala",
      "Larimichthys croceus",
      "Oncorhynchus mykiss",
      "Oncorhynchus kisutch",
      "Clarias gariepinus",
      "Haliotis spp",
      "Seriola quinqueradiata",
      "Macrobrachium rosenbergii",
      "Patinopecten yessoensis",
      "Penaeus monodon",
      "Epinephelus spp",
      "Trachinotus blochii",
      "Portunus spp",
      "Clarias gariepinus x C. macrocephalus",
      "Dicentrarchus labrax",
      "Siluroidei",
      "Perna viridis",
      "Acipenseridae",
      "Piaractus brachypomus",
      "Spirulina spp",
      "Metapenaeus spp",
      "Anodonta cygnea",
      "Mytilus galloprovincialis",
      "Bivalvia",
      "Bothidae",
      "Crassostrea gigas",
      "Sargassum fusiforme",
      "Penaeus japonicus",
      "Cyprinus carpio",
      "Invertebrata",
      "Channa striata",
      "Anabas testudineus",
      "Barbonymus gonionotus",
      "Oreochromis mossambicus",
      "Sparus aurata",
      "Ctenopharyngodon idellus",
      "Osteochilus hasselti",
      "Seriola spp",
      "Mercenaria mercenaria",
      "Corbicula fluminea",
      "Leiocassis longirostris",
      "Anguilla japonica",
      "Protosalanx hyalocranius",
      "Pangasius pangasius",
      "Algae",
      "Perna perna",
      "Mytilus edulis",
      "Atrina spp",
      "Thunnus orientalis",
      "Scylla olivacea",
      "Brachyura",
      "Pleuronectidae",
      "Piaractus mesopotamicus",
      "Trichogaster pectoralis",
      "Anadara granosa",
      "Labeo calbasu",
      "Psetta maxima",
      "Heteropneustes fossilis",
      "Papyrocranus afer",
      "Lutjanus argentimaculatus",
      "Helostoma temminckii",
      "Hemibagrus nemurus",
      "Lates calcarifer",
      "Leptobarbus hoeveni",
      "Arapaima gigas",
      "Osteobrama belangeri",
      "Leporinus spp",
      "Brycon amazonicus",
      "Prochilodus spp",
      "Crassostrea spp",
      "Prochilodus reticulatus",
      "Ruditapes decussatus",
      "Anguilla anguilla",
      "Colossoma macropomum",
      "Oncorhynchus tshawytscha",
      "Ostreidae",
      "Oreochromis aureus",
      "Thunnus thynnus",
      "Oreochromis macrochir",
      "Channa spp",
      "Carassius carassius",
      "Lutjanus guttatus",
      "Scylla serrata",
      "Meretrix lusoria"
    ]
  },
  {
    "key": "Gene edited",
    "value": 292,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Molluscs",
      "Freshwater fishes",
      "Aquatic plants",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "China",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Indonesia",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Japan",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "Southern Asia",
      "South-Eastern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Central Africa"
    ],
    "specie": [
      "Ruditapes philippinarum",
      "Hypophthalmichthys molitrix",
      "Catla catla",
      "Pectinidae",
      "Porphyra spp",
      "Undaria pinnatifida",
      "Kappaphycus alvarezii",
      "Pangasius spp",
      "Salmo salar",
      "Chanos chanos",
      "Gracilaria spp",
      "Oreochromis niloticus",
      "Procambarus clarkii",
      "Labeo rohita",
      "Mytilidae",
      "Sinonovacula constricta",
      "Clarias spp",
      "Osteichthyes",
      "Megalobrama amblycephala",
      "Eriocheir sinensis",
      "Mollusca",
      "Laminaria japonica",
      "Cyprinus carpio",
      "Porphyra tenera",
      "Pangasianodon hypophthalmus",
      "Channa argus",
      "Penaeus vannamei",
      "Cyprinidae",
      "Oreochromis aureus x O. niloticus",
      "Misgurnus anguillicaudatus",
      "Silurus asotus",
      "Monopterus albus",
      "Oreochromis (=Tilapia) spp",
      "Trionyx sinensis",
      "Macrobrachium nipponense",
      "Apostichopus japonicus",
      "Mugilidae",
      "Cirrhinus mrigala",
      "Larimichthys croceus",
      "Oncorhynchus mykiss",
      "Oncorhynchus kisutch",
      "Clarias gariepinus",
      "Haliotis spp",
      "Seriola quinqueradiata",
      "Macrobrachium rosenbergii",
      "Patinopecten yessoensis",
      "Penaeus monodon",
      "Epinephelus spp",
      "Trachinotus blochii",
      "Portunus spp",
      "Clarias gariepinus x C. macrocephalus",
      "Dicentrarchus labrax",
      "Siluroidei",
      "Perna viridis",
      "Acipenseridae",
      "Piaractus brachypomus",
      "Spirulina spp",
      "Metapenaeus spp",
      "Anodonta cygnea",
      "Mytilus galloprovincialis",
      "Bivalvia",
      "Bothidae",
      "Crassostrea gigas",
      "Sargassum fusiforme",
      "Penaeus japonicus",
      "Invertebrata",
      "Channa striata",
      "Anabas testudineus",
      "Barbonymus gonionotus",
      "Oreochromis mossambicus",
      "Sparus aurata",
      "Ctenopharyngodon idellus",
      "Osteochilus hasselti",
      "Seriola spp",
      "Mercenaria mercenaria",
      "Corbicula fluminea",
      "Leiocassis longirostris",
      "Anguilla japonica",
      "Protosalanx hyalocranius",
      "Pangasius pangasius",
      "Algae",
      "Perna perna",
      "Mytilus edulis",
      "Atrina spp",
      "Thunnus orientalis",
      "Scylla olivacea",
      "Brachyura",
      "Pleuronectidae",
      "Piaractus mesopotamicus",
      "Trichogaster pectoralis",
      "Anadara granosa",
      "Labeo calbasu",
      "Psetta maxima",
      "Heteropneustes fossilis",
      "Papyrocranus afer",
      "Lutjanus argentimaculatus",
      "Helostoma temminckii",
      "Hemibagrus nemurus",
      "Lates calcarifer",
      "Leptobarbus hoeveni",
      "Arapaima gigas",
      "Osteobrama belangeri",
      "Leporinus spp",
      "Eucheuma spp",
      "Brycon amazonicus",
      "Prochilodus spp",
      "Crassostrea spp",
      "Prochilodus reticulatus",
      "Ruditapes decussatus",
      "Anguilla anguilla",
      "Colossoma macropomum",
      "Oncorhynchus tshawytscha",
      "Ostreidae",
      "Oreochromis aureus",
      "Thunnus thynnus",
      "Oreochromis macrochir",
      "Channa spp",
      "Carassius carassius",
      "Lutjanus guttatus",
      "Scylla serrata",
      "Meretrix lusoria"
    ]
  }
];
