module.exports = [
  {
    "key": "Hybrids",
    "value": 298,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Middle Africa"
    ]
  },
  {
    "key": "Introgressed",
    "value": 297,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Middle Africa"
    ]
  },
  {
    "key": "Crossbred",
    "value": 297,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Middle Africa"
    ]
  },
  {
    "key": "Polyploid",
    "value": 297,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "China",
      "Indonesia",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Japan",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "South-Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Middle Africa"
    ]
  },
  {
    "key": "Monosex",
    "value": 293,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "Indonesia",
      "China",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Japan",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "South-Eastern Asia",
      "Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Middle Africa"
    ]
  },
  {
    "key": "Transgenic",
    "value": 291,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Aquatic plants",
      "Molluscs",
      "Freshwater fishes",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "Indonesia",
      "China",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Japan",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ecuador",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "South-Eastern Asia",
      "Eastern Asia",
      "Southern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Middle Africa"
    ]
  },
  {
    "key": "Gene edited",
    "value": 292,
    "ftype": [
      "Strains",
      "Varieties",
      "Captive propagated",
      "Wild sourced"
    ],
    "taxonomy": [
      "Molluscs",
      "Freshwater fishes",
      "Aquatic plants",
      "Diadromous fishes",
      "Crustaceans",
      "Miscellaneous aquatic animals",
      "Marine fishes"
    ],
    "country": [
      "China",
      "India",
      "Philippines",
      "Viet Nam",
      "Norway",
      "Indonesia",
      "Egypt",
      "Bangladesh",
      "Korea, Republic of",
      "Chile",
      "Korea, Dem. People's Rep",
      "Ecuador",
      "Thailand",
      "Iran (Islamic Rep. of)",
      "Nigeria",
      "Mexico",
      "Japan",
      "Turkey",
      "Faroe Islands",
      "Myanmar",
      "Italy",
      "United States of America",
      "Cambodia",
      "France",
      "Peru",
      "Australia",
      "Colombia",
      "Russian Federation",
      "Saudi Arabia",
      "Uganda",
      "Canada",
      "Malaysia",
      "Taiwan Province of China",
      "Honduras",
      "Lao People's Dem. Rep.",
      "Pakistan",
      "Nicaragua",
      "Ireland",
      "Poland",
      "Brazil",
      "Germany",
      "Tunisia",
      "Cuba",
      "Sri Lanka",
      "Costa Rica",
      "Solomon Islands",
      "Tanzania, United Rep. of",
      "Spain",
      "Uzbekistan",
      "Papua New Guinea",
      "Kiribati",
      "Ghana",
      "Rwanda",
      "Congo, Dem. Rep. of the",
      "Netherlands",
      "Sweden",
      "Portugal",
      "New Zealand",
      "Timor-Leste",
      "Burundi",
      "Croatia",
      "Syrian Arab Republic",
      "Zambia",
      "Lebanon",
      "Bolivia (Plurinat.State)",
      "Kyrgyzstan",
      "Greece",
      "US Virgin Islands",
      "Iceland",
      "Czechia",
      "United Kingdom"
    ],
    "continent": [
      "Asia",
      "Europe",
      "Africa",
      "Americas",
      "Oceania"
    ],
    "region": [
      "Eastern Asia",
      "Southern Asia",
      "South-Eastern Asia",
      "Northern Europe",
      "Northern Africa",
      "South America",
      "Western Africa",
      "Central America",
      "Western Asia",
      "Southern Europe",
      "Northern America",
      "Western Europe",
      "Australia and New Zealand",
      "Eastern Europe",
      "Eastern Africa",
      "Caribbean",
      "Melanesia",
      "Central Asia",
      "Micronesia",
      "Middle Africa"
    ]
  }
];
